name: UltimateStreaks
version: '1.0.0'
main: me.bughatti.ultimatestreaks.UltimateStreaks
api-version: '1.20'
author: Bughatti
description: Plugin de rachas (streaks) diarias

commands:
  ultimatestreaks:
    description: Comando principal de UltimateStreaks
    aliases: [us, ustreaks, streak, racha]
    usage: /<command> help

permissions:
  ultimatestreaks.claim:
    description: Permite reclamar rachas diarias
    default: true
  ultimatestreaks.give:
    description: Permite darle una racha a otro jugador
    default: op
  ultimatestreaks.reload:
    description: Permite recargar la configuración
    default: op
